camunda:
  bpm:
    filter:
      create: All Tasks
    authorization:
      enabled: false
    webapp:
      index-redirect-enabled: true
      application-path: "/"
    database:
      type: postgres
  #    admin-user:
  #      id: admin
#      password: admin
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/registration"
    username: postgres
    password: password123
    driverClassName: org.postgresql.Driver
    hikari:
      driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
  appication:
    name: opal-registration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-395868.okta.com/oauth2/default
      client:
        registration:
          okta:
            scope: "openid,profile"
            client-id: 0oa8wfcap66aOVCKD357
            client-secret: kZQ0lTv914jcEl8mpjwLLTukDCHamFnzdciSJKmo
            issuer: https://dev-395868.okta.com/oauth2/default
        provider:
          okta:
            scope: "openid,profile"
            issuer: https://dev-395868.okta.com/oauth2/default
            authorization-uri: https://dev-395868.okta.com/oauth2/default/v1/authorize
            token-uri: https://dev-395868.okta.com/oauth2/default/v1/token
            user-info-uri: https://dev-395868.okta.com/oauth2/default/v1/userinfo
            user-name-attribute: preferred_username
            jwk-set-uri: https://dev-395868.okta.com/oauth2/default/v1/keys
debug: true
okta:
  oauth2:
    issuer: https://dev-395868.okta.com/oauth2/default
    scope: "openid,profile"
