camunda:
  bpm:
    filter:
      create: All Tasks
    authorization:
      enabled: false
    webapp:
      index-redirect-enabled: true
      application-path: "/"
    database:
      type: postgres
  #    admin-user:
  #      id: admin
#      password: admin
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/registration"
    username: postgres
    password: password123
    driverClassName: org.postgresql.Driver
    hikari:
      driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
  appication:
    name: opal-registration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://test-iam.hdi.de/oauth2/ausbkkaliR0HeozMB0x6
      client:
        registration:
          okta:
            scope: "openid,profile"
            client-id: 0oabfdni7usMUrUAV0x6
            client-secret: 4FVimNVHkuetqEq18-jesC5ZgFftIS0cMMErlNj5
            issuer: https://test-iam.hdi.de/oauth2/ausbkkaliR0HeozMB0x6
            audience: api://opal
        provider:
          okta:
            scope: "openid,profile"
            issuer: https://test-iam.hdi.de/oauth2/ausbkkaliR0HeozMB0x6
            authorization-uri: https://test-iam.hdi.de/oauth2/ausbkkaliR0HeozMB0x6/v1/authorize
            token-uri: https://test-iam.hdi.de/oauth2/ausbkkaliR0HeozMB0x6/v1/token
            user-info-uri: https://test-iam.hdi.de/oauth2/default/v1/userinfo
            user-name-attribute: preferred_username
            jwk-set-uri: https://test-iam.hdi.de/oauth2/ausbkkaliR0HeozMB0x6/v1/keys
debug: true
okta:
  oauth2:
    issuer: https://test-iam.hdi.de/oauth2/ausbkkaliR0HeozMB0x6
    scopes: "openid,profile"
    audience: api://opal
 